server:
  port: 8086
  
spring:
  profiles:
    active: dev
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://localhost:27017/
      database: client-service
      auditing:
          enabled: true 