server:
  port: 8085

spring:
  profiles:
    active: prd
  application:
    name: @project.name@
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: http://localhost:8081
          predicates:
            - Path=/v1/**
        - id: transaction-service
          uri: http://localhost:8083
          predicates:
            - Path=/v1/**
        - id: credit-service
          uri: http://localhost:8084
          predicates:
            - Path=/v1/**
        - id: customer-service
          uri: http://localhost:8082
          predicates:
            - Path=/v1/**

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*'
