server:
  port: 8083
  
spring:
  profiles:
    active: dev
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://localhost:27017/
      database: transaction-service
      auditing:
          enabled: true 

  cloud:
    eureka:
      client:
        serviceUrl:
          defaultZone: http://localhost:8761/eureka/ 
        fetchRegistry: true 
        registerWithEureka: true  
        enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        eventConsumerBufferSize: 10
        registerHealthIndicator: true
    instances:
      transaction-service:
        baseConfig: default
  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 1s
    instances:
      transaction-service:
        baseConfig: default
  timelimiter:
    configs:
      default:
        timeoutDuration: 2s
        cancelRunningFuture: true
    instances:
      transaction-service:
        baseConfig: default