server:
  port: 8081

spring:
  profiles:
    active: dev
  application:
    name: bank-account-service
  data:
    mongodb:
      auto-index-creation: true
      #uri: mongodb://host.docker.internal:27017/
      uri: mongodb://localhost:27017/
      database: bank-account-service

  cloud:
    eureka:
      client:
        serviceUrl:
          defaultZone: http://localhost:8761/eureka/ 
          #defaultZone: http://host.docker.internal:8761/eureka/
        fetchRegistry: true 
        registerWithEureka: true  
        enabled: true

  kafka:
  bootstrap-servers: localhost:9092
  producer:
    value-serializer: org.apache.kafka.common.serialization.StringSerializer
  consumer:
    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    auto-offset-reset: earliest
  properties:
    security:
      protocol: PLAINTEXT
    sasl:
      mechanism: PLAIN
      jaas:
        config: org.apache.kafka.common.security.scram.ScramLoginModule required username="admin" password="admin-secret"
      
resilience4j:
  circuitbreaker:
    configs:
      default:
        failureRateThreshold: 50 # umbral de tasa de fallos
        waitDurationInOpenState: 5s # duración en estado abierto
        permittedNumberOfCallsInHalfOpenState: 3 # número permitido de llamadas en estado medio abierto
        minimumNumberOfCalls: 5 # número mínimo de llamadas para activar el cálculo del circuito
        slidingWindowType: COUNT_BASED # tipo de ventana deslizante (COUNT_BASED o TIME_BASED)
        slidingWindowSize: 10 # tamaño de la ventana deslizante
        eventConsumerBufferSize: 10 # tamaño del buffer de eventos
        registerHealthIndicator: true # registrar el indicador de salud de CircuitBreaker
    instances:
      account-service:
        baseConfig: default
  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 1s
    instances:
      account-service:
        baseConfig: default
  timelimiter:
    configs:
      default:
        timeoutDuration: 2s
        cancelRunningFuture: true
    instances:
      account-service:
        baseConfig: default

feign:
  client:
    config:
      transaction-service:
        url: http://localhost:8083
      customer-service:
        url: http://localhost:8082
      credit-service:
        url: http://localhost:8084

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
