server:
  port: 8081
spring:
  profiles:
    active: dev
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://localhost:27017/
      database: bank-account-service

feign:
  client:
    config:
      transaction-service:
        url: http://localhost:8083
      customer-service:
        url: http://localhost:8082
      credit-service:
        url: http://localhost:8084
