server:
  port: 8081
spring:
  profiles:
    active: dev
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://localhost:27017/
      database: bank-account-service

resilience4j:
  circuitbreaker:
    instances:
      remittance-service:
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        eventConsumerBufferSize: 10
        registerHealthIndicator: true
  retry:
    instances:
      remittance-service:
        maxAttempts: 3
        waitDuration: 1s
  timelimiter:
    instances:
      remittance-service:
        timeoutDuration: 2s
        cancelRunningFuture: true

feign:
  client:
    config:
      transaction-service:
        url: http://localhost:8083
      customer-service:
        url: http://localhost:8082
      credit-service:
        url: http://localhost:8084
