server:
  port: 8089
spring:
  profiles:
    active: dev
  
  cloud:
    eureka:
      client:
        serviceUrl:
          defaultZone: http://localhost:8761/eureka/ 
          #defaultZone: http://host.docker.internal:8761/eureka/
        fetchRegistry: true 
        registerWithEureka: true  
        enabled: true
    
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
    properties:
      security:
        protocol: PLAINTEXT
      sasl:
        mechanism: PLAIN
        jaas:
          config: org.apache.kafka.common.security.scram.ScramLoginModule required username="admin" password="admin-secret"

feign:
  client:
    config:
      transaction-service:
        url: http://localhost:8083
      account-service:
        url: http://localhost:8081
